services:
  web:
    image: giggio/rinha2501
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9999:9999"
    networks:
      - backend
      - payment-processor

networks:
  backend:
    driver: bridge
  payment-processor:
    external: true
